# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-12 11:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('alertas', '0001_initial'), ('alertas', '0002_auto_20170225_1619'), ('alertas', '0003_auto_20170225_1630'), ('alertas', '0004_auto_20170225_1643'), ('alertas', '0005_auto_20170226_1645'), ('alertas', '0006_auto_20170226_1649'), ('alertas', '0007_auto_20170226_1653'), ('alertas', '0008_auto_20170226_1734'), ('alertas', '0009_auto_20170226_1757'), ('alertas', '0010_auto_20170226_1814'), ('alertas', '0011_auto_20170226_1822'), ('alertas', '0012_auto_20170226_1822'), ('alertas', '0013_auto_20170226_1822'), ('alertas', '0014_auto_20170226_1823'), ('alertas', '0015_lbinvoice_nif'), ('alertas', '0016_alertasconfig'), ('alertas', '0017_auto_20170226_2003'), ('alertas', '0018_auto_20170226_2024'), ('alertas', '0019_auto_20170226_2025'), ('alertas', '0020_auto_20170305_2320')]

    initial = True

    dependencies = [
        ('borme', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaActo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('con', 'Concursos de acreedores'), ('liq', 'Liquidación de empresas'), ('new', 'Empresas de nueva creación')], max_length=3)),
                ('provincia', models.CharField(choices=[('1', 'Álava'), ('2', 'Albacete'), ('3', 'Alicante'), ('4', 'Almería'), ('5', 'Ávila'), ('6', 'Badajoz'), ('7', 'Islas Baleares'), ('8', 'Barcelona'), ('9', 'Burgos'), ('10', 'Cáceres'), ('11', 'Cádiz'), ('12', 'Castellón'), ('13', 'Ciudad Real'), ('14', 'Córdoba'), ('15', 'La Coruña'), ('16', 'Cuenca'), ('17', 'Gerona'), ('18', 'Granada'), ('19', 'Guadalajara'), ('20', 'Guipúzcoa'), ('21', 'Huelva'), ('22', 'Huesca'), ('23', 'Jaén'), ('24', 'León'), ('25', 'Lérida'), ('26', 'La Rioja'), ('27', 'Lugo'), ('28', 'Madrid'), ('29', 'Málaga'), ('30', 'Murcia'), ('31', 'Navarra'), ('32', 'Orense'), ('33', 'Asturias'), ('34', 'Palencia'), ('35', 'Las Palmas'), ('36', 'Pontevedra'), ('37', 'Salamanca'), ('38', 'Santa Cruz de Tenerife'), ('39', 'Cantabria'), ('40', 'Segovia'), ('41', 'Sevilla'), ('42', 'Soria'), ('43', 'Tarragona'), ('44', 'Teruel'), ('45', 'Toledo'), ('46', 'Valencia'), ('47', 'Valladolid'), ('48', 'Vizcaya'), ('49', 'Zamora'), ('50', 'Zaragoza'), ('51', 'Ceuta'), ('52', 'Melilla')], max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('send_html', models.BooleanField(default=True)),
                ('periodicidad', models.CharField(choices=[('weekly', 'Semanal'), ('monthly', 'Mensual'), ('daily', 'Diario')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlertaCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('send_html', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borme.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlertaPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('send_html', models.BooleanField(default=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borme.Person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LBInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('type', models.CharField(blank=True, max_length=10)),
                ('payment_type', models.CharField(choices=[('paypal', 'Paypal'), ('bank', 'Transferencia bancaria')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('is_paid', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('description', models.CharField(blank=True, max_length=2000)),
                ('nif', models.CharField(default='764223232F', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('free', 'Gratuita'), ('paid', 'Premium'), ('test', 'Período de prueba')], max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('notification_method', models.CharField(choices=[('email', 'E-mail'), ('url', 'URL')], default='email', max_length=10)),
                ('notification_email', models.EmailField(blank=True, max_length=254)),
                ('notification_url', models.URLField(blank=True)),
                ('language', models.CharField(choices=[('es', 'Español')], default='es', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='AlertasConfig',
            fields=[
                ('key', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
    ]
