# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-26 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0003_auto_20170321_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertaacto',
            name='evento',
            field=models.CharField(choices=[('liq', 'Liquidación de empresas'), ('new', 'Empresas de nueva creación')], max_length=3),
        ),
        migrations.AlterField(
            model_name='alertahistory',
            name='type',
            field=models.CharField(choices=[('liq', 'Liquidación de empresas'), ('new', 'Empresas de nueva creación'), ('company', 'Empresa'), ('person', 'Persona')], max_length=10),
        ),
    ]
