# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-26 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0005_auto_20170226_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertaacto',
            name='notification_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='alertaacto',
            name='notification_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='lbinvoice',
            name='payment_type',
            field=models.CharField(choices=[('Bank', 'Bank transfer'), ('Bitcoin', 'Bitcoin'), ('Paypal', 'Paypal')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('P', 'Premium'), ('F', 'Free')], max_length=1),
        ),
    ]
