# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-26 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0008_auto_20170226_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lbinvoice',
            name='payment_type',
            field=models.CharField(choices=[('Paypal', 'Paypal'), ('Bank', 'Bank transfer'), ('Bitcoin', 'Bitcoin')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('F', 'Free'), ('P', 'Premium')], max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notification_method',
            field=models.CharField(choices=[('E', 'E-mail'), ('U', 'URL')], default='E', max_length=1),
        ),
    ]
