# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-26 17:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0009_auto_20170226_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lbinvoice',
            name='payment_type',
            field=models.CharField(choices=[('Bank', 'Bank transfer'), ('Bitcoin', 'Bitcoin'), ('Paypal', 'Paypal')], max_length=10),
        ),
        migrations.AlterField(
            model_name='lbinvoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('P', 'Premium'), ('F', 'Free')], max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notification_method',
            field=models.CharField(choices=[('U', 'URL'), ('E', 'E-mail')], default='E', max_length=1),
        ),
    ]
