# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-26 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0010_auto_20170226_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='lbinvoice',
            name='description',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='lbinvoice',
            name='payment_type',
            field=models.CharField(choices=[('Bitcoin', 'Bitcoin'), ('Bank', 'Transferencia bancaria'), ('Paypal', 'Paypal')], max_length=10),
        ),
        migrations.AlterField(
            model_name='lbinvoice',
            name='type',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
