# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-26 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0015_lbinvoice_nif'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertasConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
    ]
