# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-26 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0016_alertasconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertasconfig',
            name='key',
            field=models.CharField(max_length=30),
        ),
    ]
