# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-26 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0017_auto_20170226_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertasconfig',
            name='id',
        ),
        migrations.AlterField(
            model_name='alertasconfig',
            name='key',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('free', 'Gratuita'), ('paid', 'Premium'), ('test', 'Período de prueba')], max_length=1),
        ),
    ]
