# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-05 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0019_auto_20170226_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('es', 'Español')], default='es', max_length=3),
        ),
        migrations.AlterField(
            model_name='alertaacto',
            name='evento',
            field=models.CharField(choices=[('con', 'Concursos de acreedores'), ('liq', 'Liquidación de empresas'), ('new', 'Empresas de nueva creación')], max_length=3),
        ),
        migrations.AlterField(
            model_name='alertaacto',
            name='periodicidad',
            field=models.CharField(choices=[('weekly', 'Semanal'), ('monthly', 'Mensual'), ('daily', 'Diario')], max_length=10),
        ),
        migrations.AlterField(
            model_name='lbinvoice',
            name='payment_type',
            field=models.CharField(choices=[('paypal', 'Paypal'), ('bank', 'Transferencia bancaria')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notification_method',
            field=models.CharField(choices=[('email', 'E-mail'), ('url', 'URL')], default='email', max_length=10),
        ),
    ]
