# Generated by Django 2.0.3 on 2018-03-12 14:42

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_anuncio', models.IntegerField()),
                ('year', models.IntegerField()),
                ('datos_registrales', models.CharField(max_length=70)),
                ('actos', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Borme',
            fields=[
                ('cve', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('url', models.URLField()),
                ('from_reg', models.IntegerField()),
                ('until_reg', models.IntegerField()),
                ('province', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=20)),
                ('anuncios', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(db_index=True, max_length=260)),
                ('nif', models.CharField(max_length=10)),
                ('slug', models.CharField(max_length=260, primary_key=True, serialize=False)),
                ('date_creation', models.DateField(blank=True, null=True)),
                ('date_extinction', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('AEIE', 'Agrupación Europea de Interés Económico'), ('AIE', 'Agrupación de Interés Económico'), ('BV', 'Besloten vennootschap met beperkte aansprakelijkheid'), ('BVBA', 'Besloten vennootschap met beperkte aansprakelijkheid'), ('COOP', 'Cooperativa'), ('FP', 'Fondo de Pensiones'), ('NV', 'Naamloze Vennootschap'), ('SA', 'Sociedad Anónima'), ('SAD', 'Sociedad Anónima Deportiva'), ('SAL', 'Sociedad Anónima Laboral'), ('SAP', 'Sociedad Anónima P?'), ('SAS', 'Sociedad por Acciones Simplificada'), ('SAU', 'Sociedad Anónima Unipersonal'), ('SC', 'Sociedad Comanditaria'), ('SCP', 'Sociedad Civil Profesional'), ('SL', 'Sociedad Limitada'), ('SLL', 'Sociedad Limitada Laboral'), ('SLLP', 'Sociedad Limitada Laboral P?'), ('SLNE', 'Sociedad Limitada Nueva Empresa'), ('SLP', 'Sociedad Limitada Profesional'), ('SLU', 'Sociedad Limitada Unipersonal'), ('SRL', 'Sociedad de Responsabilidad Limitada'), ('SRLL', 'Sociedad de Responsabilidad Limitada Laboral'), ('SRLP', 'Sociedad de Responsabilidad Limitada Profesional')], max_length=50)),
                ('date_updated', models.DateField(db_index=True)),
                ('in_bormes', django.contrib.postgres.fields.jsonb.JSONField()),
                ('anuncios', django.contrib.postgres.fields.jsonb.JSONField()),
                ('cargos_actuales_p', django.contrib.postgres.fields.jsonb.JSONField()),
                ('cargos_actuales_c', django.contrib.postgres.fields.jsonb.JSONField()),
                ('cargos_historial_p', django.contrib.postgres.fields.jsonb.JSONField()),
                ('cargos_historial_c', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField()),
                ('version', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('in_companies', django.contrib.postgres.fields.jsonb.JSONField()),
                ('in_bormes', django.contrib.postgres.fields.jsonb.JSONField()),
                ('date_updated', models.DateField(db_index=True)),
                ('cargos_actuales', django.contrib.postgres.fields.jsonb.JSONField()),
                ('cargos_historial', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='BormeLog',
            fields=[
                ('borme', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='borme.Borme')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_parsed', models.DateTimeField(blank=True, null=True)),
                ('parsed', models.BooleanField(default=False)),
                ('errors', models.IntegerField(default=0)),
                ('path', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='anuncio',
            name='borme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='borme.Borme'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='borme.Company'),
        ),
        migrations.AlterIndexTogether(
            name='anuncio',
            index_together={('id_anuncio', 'year')},
        ),
    ]
