# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-08 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borme',
            name='anuncios',
        ),
        migrations.AddField(
            model_name='anuncio',
            name='registro',
            field=models.CharField(blank=True, choices=[('A CORUÑA', 'La Coruña'), ('EIVISSA', 'Ibiza (Islas Baleares)'), ('LAS PALMAS', 'Las Palmas (Canarias)'), ('MAHON', 'Mahon (Menorca, Islas Baleares)'), ('PALMA DE MALLORCA', 'Palma de Mallorca'), ('PUERTO DE ARRECIFE', 'Puerto de Arrecife (Canarias)'), ('PUERTO DEL ROSARIO', 'Puerto del Rosario (Canarias)'), ('SAN SEBASTIAN DE LA GOMERA', 'Santa Cruz de Tenerife (Canarias)'), ('SANTA CRUZ DE LA PALMA', 'Santa Cruz de la Palma (Canarias)'), ('SANTA CRUZ DE TENERIFE', 'Santa Cruz de Tenerife (Canarias)'), ('SANTIAGO DE COMPOSTELA', 'Santiago de Compostela (La Coruña)'), ('VALVERDE', 'Santa Cruz de Tenerife (Canarias)')], max_length=50, null=True),
        ),
    ]
