# Generated by Django 2.0.3 on 2018-04-24 22:48

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='document',
            field=django.contrib.postgres.search.SearchVectorField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='document',
            field=django.contrib.postgres.search.SearchVectorField(db_index=True, null=True),
        ),
    ]
