# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-07 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borme', '0002_company_is_active_default_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='date_extinction',
            field=models.DateField(blank=True, null=True),
        ),
    ]
