# Generated by Django 2.0.3 on 2018-05-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borme', '0003_slugfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borme',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
