# Generated by Django 2.0.7 on 2018-07-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borme', '0004_index_borme_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='nif',
        ),
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('AEIE', 'Agrupación Europea de Interés Económico'), ('AIE', 'Agrupación de Interés Económico'), ('BV', 'Besloten vennootschap met beperkte aansprakelijkheid'), ('BVBA', 'Besloten vennootschap met beperkte aansprakelijkheid'), ('COOP', 'Cooperativa'), ('FP', 'Fondo de Pensiones'), ('LTD', 'Limited company'), ('NV', 'Naamloze Vennootschap'), ('S.COM.', 'Sociedad Comanditaria'), ('S.COM.P.A.', 'Sociedad Comanditaria por Acciones'), ('SA', 'Sociedad Anónima'), ('SAD', 'Sociedad Anónima Deportiva'), ('SAL', 'Sociedad Anónima Laboral'), ('SAP', 'Sociedad Anónima P?'), ('SAS', 'Sociedad por Acciones Simplificada'), ('SAU', 'Sociedad Anónima Unipersonal'), ('SC', 'Sociedad Colectiva'), ('SCP', 'Sociedad Civil Profesional'), ('SICAV', 'Sociedad de Inversión de Capital Variable'), ('SL', 'Sociedad Limitada'), ('SLL', 'Sociedad Limitada Laboral'), ('SLLP', 'Sociedad Limitada Laboral P?'), ('SLNE', 'Sociedad Limitada Nueva Empresa'), ('SLP', 'Sociedad Limitada Profesional'), ('SLU', 'Sociedad Limitada Unipersonal'), ('SME', 'Sociedad Mercantil Estatal'), ('SRL', 'Sociedad de Responsabilidad Limitada'), ('SRLL', 'Sociedad de Responsabilidad Limitada Laboral'), ('SRLP', 'Sociedad de Responsabilidad Limitada Profesional')], max_length=50),
        ),
    ]
