# Generated by Django 2.0.3 on 2018-08-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borme', '0005_auto_20180704_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_active',
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('active', 'Activa'), ('suspended', 'Cierre de hoja registral'), ('inactive', 'Extinguida')], default='active', max_length=50),
        ),
    ]
