# Generated by Django 2.0.3 on 2018-08-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borme', '0006_company_status_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='date_dissolution',
            field=models.DateField(blank=True, null=True),
        ),
    ]
