# Generated by Django 2.0.3 on 2018-09-11 20:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borme', '0008_company_auditors'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='liquidators',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='company',
            name='reason_dissolution',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
