# Generated by Django 2.0.3 on 2018-09-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borme', '0009_company_liquidator_dissolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borme',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
