# Generated by Django 2.0.3 on 2018-09-24 15:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borme', '0010_borme_url_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='capital',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='domicilio',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='inicio_actividad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='nif',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='objeto',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='actos',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterUniqueTogether(
            name='anuncio',
            unique_together={('id_anuncio', 'year')},
        ),
    ]
