# Generated by Django 2.0.3 on 2018-08-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertacompany',
            name='company',
        ),
        migrations.RemoveField(
            model_name='alertacompany',
            name='user',
        ),
        migrations.RemoveField(
            model_name='alertaperson',
            name='person',
        ),
        migrations.RemoveField(
            model_name='alertaperson',
            name='user',
        ),
        migrations.AddField(
            model_name='follower',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='follower',
            name='type',
            field=models.CharField(choices=[('company', 'Empresa'), ('person', 'Persona')], max_length=10),
        ),
        migrations.DeleteModel(
            name='AlertaCompany',
        ),
        migrations.DeleteModel(
            name='AlertaPerson',
        ),
    ]
