# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-25 15:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alertas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LBInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('type', models.CharField(max_length=10)),
                ('payment_type', models.CharField(choices=[('Bank', 'Bank transfer'), ('Paypal', 'Paypal'), ('Bitcoin', 'Bitcoin')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('is_paid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='LBUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('P', 'Premium'), ('F', 'Free')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lbinvoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alertas.LBUser'),
        ),
    ]
