# Generated by Django 2.0.10 on 2019-02-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertaacto',
            name='send_html',
        ),
        migrations.AlterField(
            model_name='alertaacto',
            name='evento',
            field=models.CharField(choices=[('liq', 'Liquidación de empresas'), ('new', 'Empresas de nueva creación'), ('adm', 'Cambios de administrador')], max_length=3),
        ),
        migrations.AlterField(
            model_name='alertahistory',
            name='type',
            field=models.CharField(choices=[('liq', 'Liquidación de empresas'), ('new', 'Empresas de nueva creación'), ('adm', 'Cambios de administrador'), ('company', 'Empresa'), ('person', 'Persona')], max_length=10),
        ),
    ]
