# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-21 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0002_auto_20170321_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertahistory',
            name='provincia',
            field=models.CharField(blank=True, choices=[('1', 'Álava'), ('2', 'Albacete'), ('3', 'Alicante'), ('4', 'Almería'), ('5', 'Ávila'), ('6', 'Badajoz'), ('7', 'Islas Baleares'), ('8', 'Barcelona'), ('9', 'Burgos'), ('10', 'Cáceres'), ('11', 'Cádiz'), ('12', 'Castellón'), ('13', 'Ciudad Real'), ('14', 'Córdoba'), ('15', 'La Coruña'), ('16', 'Cuenca'), ('17', 'Gerona'), ('18', 'Granada'), ('19', 'Guadalajara'), ('20', 'Guipúzcoa'), ('21', 'Huelva'), ('22', 'Huesca'), ('23', 'Jaén'), ('24', 'León'), ('25', 'Lérida'), ('26', 'La Rioja'), ('27', 'Lugo'), ('28', 'Madrid'), ('29', 'Málaga'), ('30', 'Murcia'), ('31', 'Navarra'), ('32', 'Orense'), ('33', 'Asturias'), ('34', 'Palencia'), ('35', 'Las Palmas'), ('36', 'Pontevedra'), ('37', 'Salamanca'), ('38', 'Santa Cruz de Tenerife'), ('39', 'Cantabria'), ('40', 'Segovia'), ('41', 'Sevilla'), ('42', 'Soria'), ('43', 'Tarragona'), ('44', 'Teruel'), ('45', 'Toledo'), ('46', 'Valencia'), ('47', 'Valladolid'), ('48', 'Vizcaya'), ('49', 'Zamora'), ('50', 'Zaragoza'), ('51', 'Ceuta'), ('52', 'Melilla')], max_length=3, null=True),
        ),
    ]
