# Generated by Django 2.0.10 on 2019-02-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0002_auto_20190205_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertaacto',
            name='periodicidad',
            field=models.CharField(choices=[('weekly', 'Semanal'), ('monthly', 'Mensual'), ('daily', 'Diaria')], max_length=10),
        ),
        migrations.AlterField(
            model_name='alertahistory',
            name='periodicidad',
            field=models.CharField(blank=True, choices=[('weekly', 'Semanal'), ('monthly', 'Mensual'), ('daily', 'Diaria')], max_length=10, null=True),
        ),
    ]
