# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-25 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0002_auto_20170225_1619'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LBUser',
            new_name='Profile',
        ),
    ]
