# Generated by Django 2.0.10 on 2019-02-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0003_auto_20190206_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertaacto',
            name='periodicidad',
            field=models.CharField(choices=[('daily', 'Diaria'), ('weekly', 'Semanal')], max_length=10),
        ),
        migrations.AlterField(
            model_name='alertahistory',
            name='periodicidad',
            field=models.CharField(blank=True, choices=[('daily', 'Diaria'), ('weekly', 'Semanal')], max_length=10, null=True),
        ),
    ]
