# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-17 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0004_auto_20170326_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='send_html',
            field=models.BooleanField(default=True),
        ),
    ]
