# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-23 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0005_profile_send_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrebormeLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('component', models.CharField(max_length=100)),
                ('log', models.CharField(max_length=1000)),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
