# Generated by Django 2.0.10 on 2019-02-13 17:54

import django.contrib.postgres.fields.jsonb
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0002_auto_20180627_1121'),
        ('alertas', '0005_auto_20190210_2238'),
    ]

    operations = [
        migrations.RenameModel('AlertaActo', 'UserSubscription'),
        migrations.AlterField(
            model_name='usersubscription',
            name='provincia',
            field=models.CharField(choices=[('1', 'Álava'), ('2', 'Albacete'), ('3', 'Alicante'), ('4', 'Almería'), ('5', 'Ávila'), ('6', 'Badajoz'), ('7', 'Islas Baleares'), ('8', 'Barcelona'), ('9', 'Burgos'), ('10', 'Cáceres'), ('11', 'Cádiz'), ('12', 'Castellón'), ('13', 'Ciudad Real'), ('14', 'Córdoba'), ('15', 'La Coruña'), ('16', 'Cuenca'), ('17', 'Gerona'), ('18', 'Granada'), ('19', 'Guadalajara'), ('20', 'Guipúzcoa'), ('21', 'Huelva'), ('22', 'Huesca'), ('23', 'Jaén'), ('24', 'León'), ('25', 'Lérida'), ('26', 'La Rioja'), ('27', 'Lugo'), ('28', 'Madrid'), ('29', 'Málaga'), ('30', 'Murcia'), ('31', 'Navarra'), ('32', 'Orense'), ('33', 'Asturias'), ('34', 'Palencia'), ('35', 'Las Palmas'), ('36', 'Pontevedra'), ('37', 'Salamanca'), ('38', 'Santa Cruz de Tenerife'), ('39', 'Cantabria'), ('40', 'Segovia'), ('41', 'Sevilla'), ('42', 'Soria'), ('43', 'Tarragona'), ('44', 'Teruel'), ('45', 'Toledo'), ('46', 'Valencia'), ('47', 'Valladolid'), ('48', 'Vizcaya'), ('49', 'Zamora'), ('50', 'Zaragoza'), ('51', 'Ceuta'), ('52', 'Melilla'), ('all', 'Todas las provincias')], max_length=100),
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(choices=[('1', 'Álava'), ('2', 'Albacete'), ('3', 'Alicante'), ('4', 'Almería'), ('5', 'Ávila'), ('6', 'Badajoz'), ('7', 'Islas Baleares'), ('8', 'Barcelona'), ('9', 'Burgos'), ('10', 'Cáceres'), ('11', 'Cádiz'), ('12', 'Castellón'), ('13', 'Ciudad Real'), ('14', 'Córdoba'), ('15', 'La Coruña'), ('16', 'Cuenca'), ('17', 'Gerona'), ('18', 'Granada'), ('19', 'Guadalajara'), ('20', 'Guipúzcoa'), ('21', 'Huelva'), ('22', 'Huesca'), ('23', 'Jaén'), ('24', 'León'), ('25', 'Lérida'), ('26', 'La Rioja'), ('27', 'Lugo'), ('28', 'Madrid'), ('29', 'Málaga'), ('30', 'Murcia'), ('31', 'Navarra'), ('32', 'Orense'), ('33', 'Asturias'), ('34', 'Palencia'), ('35', 'Las Palmas'), ('36', 'Pontevedra'), ('37', 'Salamanca'), ('38', 'Santa Cruz de Tenerife'), ('39', 'Cantabria'), ('40', 'Segovia'), ('41', 'Sevilla'), ('42', 'Soria'), ('43', 'Tarragona'), ('44', 'Teruel'), ('45', 'Toledo'), ('46', 'Valencia'), ('47', 'Valladolid'), ('48', 'Vizcaya'), ('49', 'Zamora'), ('50', 'Zaragoza'), ('51', 'Ceuta'), ('52', 'Melilla'), ('all', 'Todas las provincias')], max_length=2)),
                ('event_date', models.DateField()),
                ('event', models.CharField(choices=[('liq', 'Liquidación de empresas'), ('new', 'Empresas de nueva creación'), ('adm', 'Cambios de administrador')], max_length=3)),
                ('data_json', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionevent',
            unique_together={('province', 'event', 'event_date')},
        ),
    ]

