# Generated by Django 2.0.10 on 2019-02-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0006_rename_alertaacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertahistory',
            name='periodicidad',
            field=models.CharField(blank=True, choices=[('disabled', 'Desactivado'), ('daily', 'Diariamente'), ('weekly', 'Semanalmente')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='periodicidad',
            field=models.CharField(choices=[('disabled', 'Desactivado'), ('daily', 'Diariamente'), ('weekly', 'Semanalmente')], max_length=10),
        ),
    ]
