# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-26 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0006_auto_20170226_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertaacto',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='alertaacto',
            name='notification_email',
        ),
        migrations.RemoveField(
            model_name='alertaacto',
            name='notification_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='notification',
            field=models.CharField(choices=[('E', 'E-mail'), ('U', 'URL')], default='E', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='notification_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='notification_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='lbinvoice',
            name='payment_type',
            field=models.CharField(choices=[('Paypal', 'Paypal'), ('Bitcoin', 'Bitcoin'), ('Bank', 'Bank transfer')], max_length=10),
        ),
    ]
