# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-26 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0007_auto_20170226_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='notification',
            new_name='notification_method',
        ),
        migrations.AlterField(
            model_name='lbinvoice',
            name='payment_type',
            field=models.CharField(choices=[('Bank', 'Bank transfer'), ('Paypal', 'Paypal'), ('Bitcoin', 'Bitcoin')], max_length=10),
        ),
    ]
