# Generated by Django 2.0.3 on 2018-05-31 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0007_auto_20170423_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertaacto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alertacompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='borme.Company'),
        ),
        migrations.AlterField(
            model_name='alertacompany',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alertahistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alertaperson',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='borme.Person'),
        ),
        migrations.AlterField(
            model_name='alertaperson',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lbinvoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
