# Generated by Django 2.0.10 on 2019-03-04 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0007_periodicidad_disable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='stripe_subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.Subscription'),
        ),
    ]
