# Generated by Django 2.0.10 on 2019-03-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0008_stripesubscription_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
