# Generated by Django 2.0.3 on 2018-05-31 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0008_auto_20180601_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
