# Generated by Django 2.0.10 on 2019-03-06 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0009_usersubscription_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertahistory',
            old_name='periodicidad',
            new_name='send_email',
        ),
        migrations.RenameField(
            model_name='usersubscription',
            old_name='periodicidad',
            new_name='send_email',
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='stripe_subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lb_subscription', to='djstripe.Subscription'),
        ),
    ]
