# Generated by Django 2.0.10 on 2019-03-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0010_periodicidad_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='ip',
            field=models.GenericIPAddressField(null=True, unpack_ipv4=True),
        ),
        migrations.AlterField(
            model_name='alertahistory',
            name='send_email',
            field=models.CharField(blank=True, choices=[('disabled', 'No'), ('daily', 'Diariamente')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='send_email',
            field=models.CharField(choices=[('disabled', 'No'), ('daily', 'Diariamente')], max_length=10),
        ),
        migrations.DeleteModel(
            name='LBInvoice',
        ),
    ]
