# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-26 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0018_auto_20170226_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('free', 'Gratuita'), ('paid', 'Premium'), ('test', 'Período de prueba')], max_length=4),
        ),
    ]
