# Generated by Django 2.0.10 on 2019-02-03 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('plain_text', models.TextField()),
                ('html_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('es', 'Español')], default='es', max_length=3)),
                ('notification_method', models.CharField(choices=[('email', 'E-mail'), ('url', 'URL')], default='email', max_length=10)),
                ('notification_email', models.EmailField(blank=True, max_length=254)),
                ('notification_url', models.URLField(blank=True)),
                ('send_html', models.BooleanField(default=True)),
                ('home_phone', models.CharField(blank=True, max_length=20)),
                ('account_type', models.CharField(choices=[('individual', 'Particular'), ('company', 'Empresa')], default='company', max_length=20)),
                ('razon_social', models.CharField(blank=True, max_length=200)),
                ('cif_nif', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('post_code', models.CharField(blank=True, max_length=20)),
                ('poblacion', models.CharField(blank=True, max_length=50)),
                ('provincia', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(choices=[('ES', 'España')], default='ES', max_length=50)),
                ('newsletter_promotions', models.BooleanField(default=False)),
                ('newsletter_features', models.BooleanField(default=False)),
                ('has_api_enabled', models.BooleanField(default=False)),
                ('has_tried_subscriptions', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
