# Generated by Django 2.0.10 on 2019-02-06 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreborme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='notification_email',
        ),
    ]
