# Generated by Django 2.0.3 on 2018-07-14 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreborme', '0002_auto_20180704_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='account_type',
        ),
    ]
