# Generated by Django 2.0.3 on 2018-08-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreborme', '0003_remove_profile_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plain_text', models.TextField()),
                ('html_text', models.TextField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
