# Generated by Django 2.0.3 on 2018-11-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreborme', '0005_profile_facturacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='newsletter_features',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='newsletter_promotions',
            field=models.BooleanField(default=False),
        ),
    ]
