# Generated by Django 2.0.3 on 2018-11-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreborme', '0006_profile_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='poblacion',
        ),
        migrations.AddField(
            model_name='profile',
            name='provincia',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
