# Generated by Django 2.0.3 on 2018-11-04 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreborme', '0007_profile_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='work_phone',
        ),
    ]
