# Generated by Django 2.0.3 on 2018-11-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreborme', '0008_remove_profile_work_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_tried_subscriptions',
            field=models.BooleanField(default=False),
        ),
    ]
